website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import func, desc
from .models import Project, LoggerTag, Employee, TimeLog, Phone
from .extension import db

views = Blueprint('views', __name__)

#URL for routes
@views.route('/', methods = ['POST','GET'])
@views.route('/time-logger', methods = ['POST','GET'])
#Cant access home until login
@login_required
def home():
    timelogger = TimeLog.query.order_by(TimeLog.id).all()
    return render_template("time-logger.html", timelogger = timelogger)


@views.route('/employees', methods = ['GET'])
@login_required
def employees():
    employees = Employee.query.all()
    loggertags = LoggerTag.query.all()
    phones = Phone.query.all()
    projects = Project.query.all()
    return render_template("employees.html", employees = employees, loggertags = loggertags, phones = phones, projects = projects)

@views.route('/employees/new', methods = ['POST'])
@login_required
def employees_new():

    data_list = []
    new_data_list = []

    employee_name = request.form['EmployeeName']
    employee_lastname = request.form['EmployeeLastname']
    employee_loggertag_id = request.form['EmployeeLoggertag']
    employee_phone_id = request.form['EmployeePhone']
    employee_project_id = request.form['EmployeeProject']

    data_list.append(employee_name)
    data_list.append(employee_lastname)
    data_list.append(employee_loggertag_id)
    data_list.append(employee_phone_id)
    data_list.append(employee_project_id)

    for i in data_list:
        if i == '':
            i = None
            new_data_list.append(i)
        else:
            new_data_list.append(i)


    new_employee = Employee(name = employee_name, lastname = employee_lastname, logger_tag_id = new_data_list[2],phone_id = new_data_list[3], project_id = new_data_list[4])
    db.session.add(new_employee)
    db.session.commit()
    db.session.close()
    return redirect(url_for('views.employees'))

@views.route('/projects', methods = ['POST','GET'])
@login_required
def projects():
    projects = Project.query.all()
    return render_template("projects.html", projects = projects)

@views.route('/loggertags', methods = ['GET'])
@login_required
def loggertags():
    loggertag = LoggerTag.query.order_by(LoggerTag.id).all()
    return render_template("loggertags.html", loggertag = loggertag)

@views.route('/phones', methods = ['GET'])
@login_required
def phones():
    phones = Phone.query.order_by(Phone.id).all()
    return render_template("phones.html", phones = phones)


@views.route('/phones/new', methods = ['POST'])
@login_required
def phone_new():
    phone_model = request.form['PhoneModel']
    phone_imei = request.form['PhoneIMEI']
    new_phone = Phone(id = '', name = phone_model, comp_id = phone_imei)
    db.session.add(new_phone)
    db.session.commit()
    db.session.close()
    return redirect(url_for('views.phones'))

'''
@views.route('/time-logger', methods = ['POST','GET'])
@login_required
def time_logger():
        return render_template("time-logger.html")

'''

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Base{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/main.css">

    </head>


    <body>
        <script type="text/jacascript" src={{ url_for('static', filename='index.js') }}></script>


        <div class="container">

        {% block content %}



        {% endblock %}

        <div class="container" bis_skin_checked="1" style = "position:fixed;bottom:1px;width:100%; margin_top: 30px;">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top" style="width:100%;">
            <p class="col-md-4 mb-0 text-muted">© 2022 Powered by Paweł Sopuch</p>

          </footer>
        </div>

        </div>





    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="/static/index.js"></script>
    </body>
    </br>
    <!--<div class="container">
        <div class="container" bis_skin_checked="1" style = "position:fixed;bottom:1px;width:100%; margin_top: 30px;">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top" style="width:100%;">
            <p class="col-md-4 mb-0 text-muted">© 2022 Powered by Paweł Sopuch</p>

          </footer>
        </div>
    </div> -->

website/templates/employees.html
{% extends "base.html" %}
<title>{% block title %}Employees{% endblock %}</title>
{% block content %}
    <nav class="navbar navbar-expand-xxl navbar-light bg-light">
      <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <a class = "nav-link" href = "{{url_for('views.home')}}" type="button" >Time logger</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class = "nav-link active" href = "{{url_for('views.employees')}}" type="button" >Employees</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class = "nav-link" href = "{{url_for('views.projects')}}" type="button" >Projects</a>
          </li>
          <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.loggertags')}}" type="button" >Logger Tags</a>
          </li>
          <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.phones')}}" type="button" >Phones</a>
              </li>
        </ul>
    </nav>

    <div class="container">
        </br></br>

        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">
            Create new employee
        </button>

        </br></br>
        <!-- Detailed employee view -->
        <form action="/search" method="POST">
            <label for="exampleDataList" class="form-label">Find employee</label>
            <input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Type employee" autocomplete="off" name="search_field">
            <datalist id="datalistOptions">
                {% for employee in employees %}
              <option value="{{ employee.name }} {{employee.lastname}}">
                {% endfor %}
            </datalist>

            </br>
            <div style = "display: inline-flex">
            <button type="submit" class="btn btn-primary">Find</button>
        </form>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">New employee</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="post" action="/employees/new">
                <div class="form-group">
                    <label for="formGroupExampleInput">Name</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" name = "EmployeeName" placeholder="Type name" autocomplete="off" required>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Lastname</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" name= "EmployeeLastname" placeholder="Type lastname" autocomplete="off" required>
                </div>
                <div class="form-group">
                    <label for="EmployeeLoggertag">Choose loggertag:</label>
                    <input list="EmployeeLoggertagList" class="form-control" name="EmployeeLoggertag" id="EmployeeLoggertag" placeholder="Choose tag" autocomplete="off" />
                    <datalist id="EmployeeLoggertagList">
                        {% for loggertag in loggertags %}
                        <option value= "{{ loggertag.id }}">Id: {{loggertag.id}} | Serial: {{ loggertag.serial }}</option>
                        {% endfor %}

                    </datalist>
                </div>

                <div class="form-group">
                    <label for="EmployeePhone">Choose phone:</label>
                    <input list="EmployeePhoneList" class="form-control" name="EmployeePhone" id="EmployeePhone" placeholder="Choose phone" autocomplete="off" />
                    <datalist id="EmployeePhoneList">
                        {% for phone in phones %}
                        <option value= "{{ phone.id }}">Name: {{ phone.name }} | Company ID: {{ phone.comp_id }}</option>
                        {% endfor %}

                    </datalist>
                </div>

                <div class="form-group">
                    <label for="EmployeeProject">Choose project:</label>
                    <input list="EmployeeProjectList" class="form-control" name="EmployeeProject" id="EmployeeProject" placeholder="Choose project" autocomplete="off" />
                    <datalist id="EmployeeProjectList">
                        {% for project in projects %}
                        <option value= "{{ project.id }}">{{ project.name }} | {{ project.country }}</option>
                        {% endfor %}

                    </datalist>
                </div>




          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" name="">Save changes</button>
          </div>
            </form>


        </div>
      </div>
    </div>


    <div class="container">
        </br></br>
        <table class="table" style="text-align:center;">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Fullname</th>
              <th scope="col">Project</th>
              <th scope="col">Loggertag ID</th>
              <th scope="col">Phone ID</th>
              <th scope="col">Project ID</th>
            </tr>
          </thead>
          <tbody>
            {% for employee in employees %}
            <tr>

              <th scope="row">{{ employee.id }}</th>
              <td>{{ employee.name }}</td>
              <td>{{ employee.lastname }}</td>
              <td>{{ employee.project }}</td>
              <td>{{ employee.logger_tag_id }}</td>
              <td>{{ employee.phone_id }}</td>
              <td>{{ employee.project_id }}</td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}
<title>{% block title %}Home{% endblock %}</title>
{% block content %}
<nav class="navbar navbar-expand-xxl navbar-light bg-light">
          <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class = "nav-link" href = "{{url_for('views.home')}}" type="button" >Time logger</button>
      </li>
    </ul>
</nav>
{% endblock %}

website/templates/loggertags.html
{% extends "base.html" %}
<title>{% block title %}Logger Tags{% endblock %}</title>


{% block content %}
        <nav class="navbar navbar-expand-xxl navbar-light bg-light">
          <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.home')}}" type="button" >Time logger</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.employees')}}" type="button" >Employees</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.projects')}}" type="button" >Projects</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link active" href = "{{url_for('views.loggertags')}}" type="button" >Logger Tags</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.phones')}}" type="button" >Phones</a>
              </li>
            </ul>
        </nav>

        </br></br>
        <div class="container">
            </br></br>
            <table class="table" style="text-align:center;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Serial</th>
                </tr>
              </thead>
              <tbody>
                  {% for tag in loggertag %}
                <tr>
                  <th scope="row">{{ tag.id }}</th>
                  <td>{{ tag.serial }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

{% endblock %}

website/templates/loggertools.html
{% extends "base.html" %}
<title>{% block title %}Logger Tags{% endblock %}</title>


{% block content %}
        <nav class="navbar navbar-expand-xxl navbar-light bg-light">
          <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.home')}}" type="button" >Time logger</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.employees')}}" type="button" >Employees</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.projects')}}" type="button" >Projects</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link active" href = "{{url_for('views.loggertags')}}" type="button" >Logger Tags</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.phones')}}" type="button" >Phones</a>
              </li>
            </ul>
        </nav>

        </br></br>
        <div class="container">
            </br></br>
            <table class="table" style="text-align:center;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Serial</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                {% for tag in loggertags %}
                  <th scope="row">{{ tool.id }}</th>
                  <td>{{ tool.serial }}</td>
                {% endfor %}
                </tr>
              </tbody>
            </table>
        </div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
<title>{% block title %}Login{% endblock %}</title>
{% block content %}
<form action="/login" method="POST">
    <div class="align-middle" style="padding-top:4.5rem;width:39vw;margin:auto;">
        <div class="container">
            <div class="mb-3 row">
                <label for="staticEmail" class="col-sm-2 col-form-label"><b>Login</b></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-control-sm" id="inputLogin" value="" name="login_form">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="inputPassword" class="col-sm-2 col-form-label"><b>Password</b></label>
                <div class="col-sm-10">
                    <input type="password" class="form-control form-control-sm" id="inputPassword" name="password_form">
                </div>
            </div>
        </div>
    </div>
    </br></br></br>
    <div class="d-grid gap-2 col-6 mx-auto" style="width: 17%;">
        <button class="btn btn-primary" style="--bs-btn-padding-y: .65rem; --bs-btn-padding-x: .7rem; --bs-btn-font-size: .85rem;" type="submit" name="login_button">Login</button>
    </div>
</form>
{% endblock %}

website/templates/phones.html
{% extends "base.html" %}
<title>{% block title %}Phones{% endblock %}</title>


{% block content %}
        <nav class="navbar navbar-expand-xxl navbar-light bg-light">
          <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.home')}}" type="button" >Time logger</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.employees')}}" type="button" >Employees</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.projects')}}" type="button" >Projects</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.loggertags')}}" type="button" >Logger Tags</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link active" href = "{{url_for('views.phones')}}" type="button" >Phones</a>
              </li>
            </ul>
        </nav>


<!--

        </br></br>
        <div class="container">
            # Detailed project view
            <form action="/search" method="POST">
              <label for="exampleDataList" class="form-label">Search project</label>
                <input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Type project" autocomplete="off" name="search_field">
                <datalist id="datalistOptions">
                    {% for phone in phones %}
                  <option value="{{ phone.imei }}">
                    {% endfor %}
                </datalist>

                </br>
                <div style = "display: inline-flex">
                <button type="submit" class="btn btn-primary">Find</button>
                <button type="submit" class="btn btn-primary" id="PhoneAddButton">Add new</button>
            </form>
        </div>
-->

    </br></br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Add phone
    </button>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">New phone</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="post" action="/phones/new">
                <div class="form-group">
                    <label for="formGroupExampleInput">Model</label>
                    <input type="text" class="form-control" id="formGroupExampleInput" name = "PhoneModel" placeholder="Type phone model" autocomplete="off" required>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Company ID</label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" name= "PhoneIMEI" placeholder="Type phone IMEI" autocomplete="off" required>
                </div>



          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" name="">Save changes</button>
          </div>
            </form>
        </div>
      </div>
    </div>


        <div class="container">
            </br></br>
            <table class="table" style="text-align:center;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Model</th>
                  <th scope="col">Company ID</th>

                </tr>
              </thead>
              <tbody>
                 {% for phone in phones %}
                <tr>
                  <th scope="row">{{ phone.id }}</th>
                  <td>{{ phone.name }}</td>
                  <td>{{ phone.comp_id }}</td>

                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

{% endblock %}

website/templates/projects.html
{% extends "base.html" %}
<title>{% block title %}Projects{% endblock %}</title>


{% block content %}
        <nav class="navbar navbar-expand-xxl navbar-light bg-light">
          <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.home')}}" type="button" >Time logger</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.employees')}}" type="button" >Employees</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link active" href = "{{url_for('views.projects')}}" type="button" >Projects</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.loggertags')}}" type="button" >Logger Tags</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.phones')}}" type="button" >Phones</a>
              </li>
            </ul>
        </nav>

        </br></br>
        <div class="container">
            <!-- Detailed project view -->
            <form action="/search" method="POST">
              <label for="exampleDataList" class="form-label">Search project</label>
                <input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Type project" autocomplete="off" name="search_field">
                <datalist id="datalistOptions">
                    {% for project in projects %}
                  <option value="{{ project.name }}">
                    {% endfor %}
                </datalist>

                </br>
                <div style = "display: inline-flex">
                <button type="submit" class="btn btn-primary">Find</button>
            </form>
        </div>

        <div class="container">
            </br></br>
            <table class="table" style="text-align:center;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Country</th>
                  <th scope="col">Project Tag</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                {% for project in projects %}
                  <th scope="row">{{ project.id }}</th>
                  <td>{{ project.name }}</td>
                  <td>{{ project.country }}</td>
                  <td>{{ project.serial }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

{% endblock %}

website/templates/time-logger.html
{% extends "base.html" %}
<title>{% block title %}Time Logger{% endblock %}</title>


{% block content %}
        <nav class="navbar navbar-expand-xxl navbar-light bg-light">
          <!-- <img src="/static/images/for_you_group.png" alt="Logo For You Group" width="300" height="auto"> -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class = "nav-link active" href = "{{url_for('views.home')}}" type="button" >Time logger</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.employees')}}" type="button" >Employees</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.projects')}}" type="button" >Projects</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.loggertags')}}" type="button" >Logger Tags</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class = "nav-link" href = "{{url_for('views.phones')}}" type="button" >Phones</a>
              </li>
            </ul>
        </nav>

        </br></br>

        <!--
        <div class="container">
             Detailed search form
            <form action="/search" method="POST">
              <label for="exampleDataList" class="form-label">Search project</label>
                <input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Type lastname" autocomplete="off" name="search_field">
                <datalist id="datalistOptions">
                    {% for project in projects %}
                  <option value="{{ project.name }}">
                    {% endfor %}
                </datalist>

                </br>
                <div style = "display: inline-flex">
                <button type="submit" class="btn btn-primary">Find</button>
            </form>
        </div>
        -->

        <div class="container">
            <label for="date" class="form-label">Choose date: </label>
            <input type="date" id="start" name="trip-start" min="2022-01-01" max="2040-12-31" value="">

            </br></br>
            <table class="table" style="text-align:center;">
              <thead>

                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Supervisor</th>
                  <th scope="col">Subordinate</th>
                  <th scope="col">Date</th>
                  <th scope="col">Time</th>
                </tr>
              </thead>
              <tbody>
                  {% for log in timelogger %}
                <tr>
                  <th scope="row">{{ log.id }}</th>
                  <td>{{ log.phone }}</td>
                  <td>{{ log.tag }}</td>
                  <td>{{ log.date }}</td>
                  <td>{{ log.time }}</td>
                </tr>
                    {% endfor %}

              </tbody>
            </table>
        </div>

{% endblock %}